<?php
namespace Giftbalogun\Kudaapitoken\Controllers;

class ServiceTypes
{
    // LIST OF API SERVICES OFFERED BY KUDA
    const ADMIN_CREATE_VIRTUAL_ACCOUNT = 'ADMIN_CREATE_VIRTUAL_ACCOUNT';
    const RETRIEVE_SINGLE_VIRTUAL_ACCOUNT = 'ADMIN_RETRIEVE_SINGLE_VIRTUAL_ACCOUNT';
    const BANK_LIST = 'BANK_LIST';
    const NAME_ENQUIRY = 'NAME_ENQUIRY';
    const SINGLE_FUND_TRANSFER = 'SINGLE_FUND_TRANSFER';
    const VIRTUAL_ACCOUNT_FUND_TRANSFER = 'VIRTUAL_ACCOUNT_FUND_TRANSFER';
    const TRANSACTION_STATUS_QUERY = 'TRANSACTION_STATUS_QUERY';
    const RETRIEVE_VIRTUAL_ACCOUNT_BALANCE = 'RETRIEVE_VIRTUAL_ACCOUNT_BALANCE';
    const ADMIN_MAIN_ACCOUNT_TRANSACTIONS = 'ADMIN_MAIN_ACCOUNT_TRANSACTIONS';
    const ADMIN_MAIN_ACCOUNT_FILTERED_TRANSACTIONS = 'ADMIN_MAIN_ACCOUNT_FILTERED_TRANSACTIONS';
    const ADMIN_VIRTUAL_ACCOUNT_TRANSACTIONS = 'ADMIN_VIRTUAL_ACCOUNT_TRANSACTIONS';
    const ADMIN_VIRTUAL_ACCOUNT_FILTERED_TRANSACTIONS = 'ADMIN_VIRTUAL_ACCOUNT_FILTERED_TRANSACTIONS';
    const FUND_VIRTUAL_ACCOUNT = 'FUND_VIRTUAL_ACCOUNT';
    const WITHDRAW_VIRTUAL_ACCOUNT = 'WITHDRAW_VIRTUAL_ACCOUNT';
    const ADMIN_RETRIEVE_MAIN_ACCOUNT_BALANCE = 'ADMIN_RETRIEVE_MAIN_ACCOUNT_BALANCE';
    const RETRIEVE_TRANSACTION_LOGS = 'RETRIEVE_TRANSACTION_LOGS';
    //KUDA SAVING API
    const RETRIEVE_SPEND_AND_SAVE_TRANSACTIONS = 'RETRIEVE_SPEND_AND_SAVE_TRANSACTIONS';
    const CREATE_PLAIN_SAVINGS = 'CREATE_PLAIN_SAVINGS';
    const GET_PLAIN_SAVINGS = 'GET_PLAIN_SAVINGS';
    const CREATE_OPEN_FLEXIBLE_SAVE = 'CREATE_OPEN_FLEXIBLE_SAVE';
    const CREATE_CLOSED_FLEXIBLE_SAVE = 'CREATE_CLOSED_FLEXIBLE_SAVE';
    const GET_ALL_CUSTOMER_PLAIN_SAVINGS = 'GET_ALL_CUSTOMER_PLAIN_SAVINGS';
    const GET_ALL_PLAIN_SAVINGS = 'GET_ALL_PLAIN_SAVINGS';
    const UPDATE_PLAIN_SAVINGS = 'UPDATE_PLAIN_SAVINGS';
    const PLAIN_SAVINGS_TRANSACTIONS = 'PLAIN_SAVINGS_TRANSACTIONS';
    const RETRIEVE_PLAIN_SAVINGS_TRANSACTIONS = 'RETRIEVE_PLAIN_SAVINGS_TRANSACTIONS';
}
